//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kmit_CandidateDetail
    {
        public int CandidateId { get; set; }
        public System.DateTime DateofInterview { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string PhoneNo { get; set; }
        public string Hometown { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> CurrentCTC { get; set; }
        public Nullable<int> ExpectedCTC { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public string Interviewer { get; set; }
        public string CommentsfromInterviewer { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateId { get; set; }
        public string Status { get; set; }
        public string CommentsfromHR { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> DateOfPhoneIntervbiew { get; set; }
        public string ReferedBy { get; set; }
    }
}
